### ISSUE TITLE
execute_script не работает

### ISSUE THREAD

**Issue by AlphaBeth** [roge111/lab5-roge111#39]
```
execute_script sc
Exception in thread "main" java.lang.NullPointerException
        at test.lab.common.Console.info(Console.java:240)
        at test.lab.common.Console.doCommand(Console.java:89)
        at test.lab.common.Console.executeCommand(Console.java:101)
        at test.lab.common.utils.ProductsManager.executeScript(ProductsManager.java:231)
        at test.lab.common.Console.executeScript(Console.java:281)
        at test.lab.common.Console.lambda$new$3(Console.java:40)
        at test.lab.common.Console.doCommand(Console.java:89)
        at test.lab.common.Console.startInteractiveMode(Console.java:79)
        at test.lab.common.Console.main(Console.java:52)
ivanuskov@helios:/home/ivanuskov/studs/2022_1/s335189/5$ cat sc
info
```

**Comment by AlphaBeth** [comment]
```
execute_script sc

help: вывести справку по доступным командам
info: вывести в стандартный поток вывода информацию о коллекции (тип, дата инициализации, количество элементов и т.д.)
show: вывести в стандартный поток вывода все элементы коллекции в строковом представлении
add: добавить новый элемент в коллекцию
update 'id': обновить элемент коллекции id которого равен заданному
remove_by_id 'id': удалить элемент из коллекции по его id
clear: очистить коллекцию
save: сохранить коллекцию в файл
execute_script 'file_name': считать и исполнить скрипт из файла file_name
exit: завершить программу
remove_first: удалить первый элемент из коллекции
head: вывести первый элемент коллекции
remove_greater 'element': удалить из коллекции все элементы превыщающие заданный
remove_all_by_manufacturer 'manufacturer': удалить из коллекции все элементы, значение поля manufacturerCost которого эквивалентно заданному
count_by_manufacturer 'manufacturer': вывести количество элементов, значение поля manufacturer которых равно заданному
count_greater_than_manufacturer 'manufacturer': вывести количество элементов, значение поля manufacturer которых больше заданного

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
        at java.util.Arrays$ArrayList.get(Arrays.java:3841)
        at test.lab.common.utils.ProductsManager.executeScript(ProductsManager.java:229)
        at test.lab.common.Console.executeScript(Console.java:281)
        at test.lab.common.Console.lambda$new$3(Console.java:40)
        at test.lab.common.Console.doCommand(Console.java:89)
        at test.lab.common.Console.startInteractiveMode(Console.java:79)
        at test.lab.common.Console.main(Console.java:52)
ivanuskov@helios:/home/ivanuskov/studs/2022_1/s335189/5$ cat sc
help
add
product name
22
21
22
33
32
LITERS
manuf
full name
PUBLIC
street
2
2
2
city

```
